### ISSUE TITLE
Some real bad errors break report generation

### ISSUE THREAD

**Issue by rklyne** [Memrise/mypy-json-report#105]
On an old and ill-typed project I got this error from the report generator.

```
> mypy . --strict | mypy-json-report parse --output-file mypy-ratchet.json
Traceback (most recent call last):
  File "/home/rk/.cache/pypoetry/virtualenvs/X-wgmWa0Al-py3.11/bin/mypy-json-report", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/rk/.cache/pypoetry/virtualenvs/X-wgmWa0Al-py3.11/lib/python3.11/site-packages/mypy_json_report.py", line 102, in main
    parsed.func(parsed)
  File "/home/rk/.cache/pypoetry/virtualenvs/X-wgmWa0Al-py3.11/lib/python3.11/site-packages/mypy_json_report.py", line 139, in _parse_command
    messages_sorted = sorted(messages, key=operator.attrgetter("filename"))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rk/.cache/pypoetry/virtualenvs/X-wgmWa0Al-py3.11/lib/python3.11/site-packages/mypy_json_report.py", line 182, in from_lines
    yield MypyMessage.from_line(line)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rk/.cache/pypoetry/virtualenvs/X-wgmWa0Al-py3.11/lib/python3.11/site-packages/mypy_json_report.py", line 194, in from_line
    filename, line_number, *_ = location.split(":")
    ^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected at least 2, got 1)
```

Running simply `mypy . --strict` showed these issues:
```tests/integration/pact_provider_states_data.py: error: Source file found twice under different module names: "pact_provider_states_data" and "tests.integration.pact_provider_states_data"
tests/integration/pact_provider_states_data.py: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#mapping-file-paths-to-modules for more info
tests/integration/pact_provider_states_data.py: note: Common resolutions include: a) adding `__init__.py` somewhere, b) using `--explicit-package-bases` or adjusting MYPYPATH
```

Using grep to suppress these proves that they are the culprit: `mypy . --strict | grep -v pact_provider_states |  mypy-json-report parse --output-file mypy-ratchet.json`

I'd send you a PR but I figure we should start with some discussion of the appropriate action in this case.

**Comment by rklyne** [comment]
My suggestion of the appropriate action would be to allow errors that don't have a line number.

An alternative would be to raise a clearer ParseError explaining that this codebase is too broken and insisting that it be improved before we can work. This is going to be in line with the user's goals but maybe not viable in their team / process.

**Comment by rklyne** [comment]
That does sound sensible but I have one concern with the idea. Such error messages wouldn't be tracked in the report file and if a developer introduces a new error of this type then it wouldn't be caught as an error. In that case I'd really want something to fail.

How about we emit those errors as you say and also return a non-zero status code?

**Comment by Tenzer** [comment]
That sounds reasonable to me. I have had a go at implementing that here: #106.

**Comment by rklyne** [comment]
Lgtm. Thanks!
