### ISSUE TITLE
Maintainer permissions

### ISSUE THREAD

**Issue by meshy** [Memrise/mypy-json-report#94]
Hi! I've just had my maintainer permissions removed on this project. I realise that this is "Copyright Memrise", but I am the original author and wish to continue contributing to this project. Can I please have my permissions restored?

**Comment by Tenzer** [comment]
It should be restored now. For some reason, your permissions hadn't been added to the Terraform configuration, so were wiped in a cleanup. That's been sorted now.

**Comment by meshy** [comment]
Thank you very much for the quick fix! :heart:
